name: todo list workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
   - name: checkout code from repository
     uses: actions/checkout@v3

   - name: Set up Node.js
     uses: actions/setup-node@v3
     with:
       node-version: '16'
   
   - name: Install dependencies
     run: npm install


   - name: Fix permissions for node_modules
     run: chmod -R 755 ./node_modules

   - name: Run tests
     run: npm test   

  

    

       